HumbleUI/JWM

README.md

Original link in README did not specify protocol, was falsely treated as a relative link.

Fix Winit link in README by adding missing https

---

linux/cc/MouseButtonX11.cc
linux/cc/MouseButtonX11.hh
linux/cc/WindowManagerX11.cc

Use the correct (at least on my Linux) button numbers; also ignores 4 & 5, because those are mouse wheel up/down while JWM doesn't have those.

X11: fix back/forward mouse buttons (closes #145)

---

linux/cc/WindowManagerX11.cc

It's weird that it worked at all before (didn't work for pasting in gnome-terminal & lwjgl though, which made me investigate)

X11: fix clipboard

---

linux/cc/WindowManagerX11.cc

Currently, the following can happen:
1. Main thread: runs `notifyBool.store(false);`
2. Auxiliary thread: runs `notifyLoop`, `notifyBool.exchange(true)` returns false; writes character to pipe & sets `notifyBool` to true
3. Main thread: clears pipe
Now the pipe is clear, but `notifyBool` is true, meaning no `notifyLoop` call will do anything, and `poll()` will never respond.
[My comment](https://github.com/HumbleUI/JWM/blob/906ec6ed4f1d96408b6e7023b8ed857a5f6016d8/linux/cc/WindowManagerX11.cc#L245) was technically correct as the events corresponding to `notifyLoop` calls between the poll & notifyBool clears will be processed, but I failed to consider what happens after that :/

X11: fix notifyLoop being called in parallel to main loop end

---

linux/cc/WindowManagerX11.cc
macos/cc/WindowMac.mm
shared/cc/MouseCursor.hh
shared/java/MouseCursor.java
windows/cc/WindowWin32.cc

warning: completely untested on macOS or windows as I don't have access to those, but I tried to find some names for the icons for those OSes anyway.
Adds resizing cursors (plus more X11 definitions for the existing ones). Names taken from [CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor).

Resizing mouse cursors

---

README.md
macos/cc/JWMWindowDelegate.mm

Implements the EventWindowFocusIn and EventWindowFocusOut events on macOS. 
It is worth noting that macOS has different types of focus: whether the application is active, whether a window accepts input (key window) and whether a window is the main window (has the active appearance). This implementation listens to 'key window' events, because this gives expectations consistent with the X11 and Windows implementations.

macOS: Implement window focus events

---

examples/dashboard/java/PanelMouseCursors.java
macos/cc/JWMMainView.mm
macos/cc/WindowMac.hh
macos/cc/WindowMac.mm

After using `setMouseCursor`, I noticed that when the cursor leaves the window and re-enters, it returns to the default arrow cursor.
The solutions to this are to use either `addCursorRect:cursor:` or `NSTrackingArea` to ensure the cursor is set back to the preferred image. This implementation builds on the existing tracking area, which I think is better than [an implementation using cursor rects](https://github.com/HumbleUI/JWM/compare/0.4.4...LuisThiamNye:JWM:luistn/cursors?expand=1).
Also, this patch includes a small modification to the dashboard example which allows you to click to the mouse cursor panel to keep the current cursor set until another element sets it back. As a result, the effect of this patch can be clearly seen.

macOS: Fix cursor resetting to arrow

---

README.md

I'm just learning about Skija+JWM, should this link point to the new repo?

Point to supported Skija in readme

---

linux/cc/AppX11.cc

Running under XWayland, or just under my setup, XResourceManagerString returns null. This avoids the XrmGetStringDatabase crash.

linux: avoid crash on empty X11 resources

---

linux/cc/WindowManagerX11.cc

see #243
Seems to work for me (linux mint 21; don't have a touchpad to test to see how this may affect it), but I don't know if this is a good approach. `classInfo->sourceid` contains the id that is received both when some mouse button is and isn't held, so this switches to using it to look up the device instead of deviceid.
(also renames loop variable to avoid confusion as it's unrelated to the actual deviceid)

X11: Potential fix for #243

---

docs/Getting Started.md

Some small Markdown fixes I saw while reading the Getting Started doc.

Docs: fix link to example, java Markdown annotations

---

linux/cc/WindowManagerX11.cc

My previous X11 PR (#244) introduced an issue where tabbing out & back into a window didn't clear the scroll valuator (just moving mouse out & in did work, which is what I had tested). I don't see a way to clear them precisely here, as neither the sourceid nor deviceid is the ID that stores the valuator, without introducing a map from device to source IDs, so this patch just clears all unconditionally.
Given that the IDs are the same between multiple JWM windows (at least on my Linux Mint 21 system), I don't think this should affect anything either.

X11: Clear all scroll valuators on XI_Enter

---

docs/windows/build.md
script/build_utils.py

Fixes javadoc "unmappable character for encoding windows-1252", which was appearing during `python scripts/package.py` on my installation. Full error:
```
Generating JavaDoc target/delomboked to target/apidocs
target\delomboked\io\github\humbleui\jwm\EventMouseScroll.java:10: error: unmappable character (0x90) for encoding windows-1252
* Direction Γå? + / ΓêÆ ΓåÆ
^
target\delomboked\io\github\humbleui\jwm\EventMouseScroll.java:65: error: unmappable character (0x90) for encoding windows-1252
* Direction Γå? + / ΓêÆ ΓåÆ
^
target\delomboked\io\github\humbleui\jwm\ZOrder.java:9: error: unmappable character (0x9D) for encoding windows-1252
/** Default ΓÇ£Always on topΓÇ? behavior */
^
3 errors
Traceback (most recent call last):
File "C:\Users\Quest\repos\humbleui\JWM\script\package.py", line …
```

Add javadoc -encoding UTF-8 to fix package.py unmappable char

---

linux/java/WindowX11.java
macos/java/WindowMac.java
shared/java/Window.java
windows/cc/WindowWin32.cc
windows/cc/WindowWin32.hh
windows/java/WindowWin32.java

These are not sufficient to _steal_ foreground application focus in Windows, which will require another commit to add attaching the JWM window to the current foreground thread.
I'll mark this as Draft until subsequent commit but I wanted to open the floor for feedback on the first commit.
The subsequent commit will need to add functionality from the top answer of https://stackoverflow.com/questions/916259/win32-bring-a-window-to-top , which needs FNs for `GetForegroundWindow`, `GetCurrentThreadId`, `GetWindowThreadProcessId`, and `AttachThreadInput`. I'll first try just adding these to the `Window` class; there might be a better architecture to refactor this to, but I'll look to @tonsky's guidance once I actually get this working.

Add Window bringToFront & isFront, Windows impl

---

macos/cc/WindowMac.mm
macos/java/WindowMac.java

Also implement IsFront with NSWindow isMainWindow
Mac equivalent to PR #266, where these two functions work to get "launcher functionality" out of my HumbleUI program. I'm also still using JNativeHook to read Alt+Space from the user's keyboard while the launcher program is in the background & then forcing it to the front via `BringToFront()`
`IsFront()` is similarly used to determine whether the launcher is _already_ in the foreground so that the launcher can self-minimize.

Add Mac bringToFront with NSApp activateIgnoringOtherApps

---

script/common.py
script/run.py

Updates Skija to 0.116.1, and makes it use the e.g. `skija-linux-x64` repo path instead of `skija-linux`; that was broken for the previous 0.109.2 too actually.

Update Skija version and fix skija_native name for non-macOS

---

linux/cc/WindowManagerX11.cc
linux/cc/WindowManagerX11.hh

Without this, on my system, the `XI_Motion` mouse events were always lagging one event behind (not just one frame, but from whenever was the last time the mouse moved, so the wrong mouse pointer could be kept indefinitely).
i.e., in this gif, whenever I'm moving the mouse back & forth a single pixel, the `XI_Motion:` logs show the previous position (i.e. moving one pixel right results in it the X coordinate decreasing).
The `XQueryPointer` values appear to be up-to-date always, however, so this patch switches to using them instead.
This effectively reduces the mouse→display latency by at least 1 frame or 16ms (which, though not the cause for me finding this, is definitely a good benefit!)

Use XQueryPointer mouse position instead of XI_Motion fields

---

linux/cc/KeyX11.cc
linux/cc/KeyX11.hh
linux/cc/WindowManagerX11.cc

Adds KeyLocation for right keys & keypad, and also adds additional Latin 1 keys mapping to shift+another key (not sure if all are strictly necessary, but it can't hurt; started by someone on a Faroese layout (`setxkbmap fo`) hitting `XK_plus` and I just added the rest from the latin-1 section).
The "shift+" part isn't particularly nice as then it's impossible to determine whether the actual shift key is pressed, but it's better than nothing.

X11: add KeyLocation, additional keys

---

linux/java/WindowX11.java

Fixes spurious errors, as the C function has a void return type, thus leaving garbage where JNI expects an object reference. Caused weird NPEs with clang++ 18 on titles longer than 23 chars.

X11: fix _nSetTitle return type

---

examples/dashboard/java/Example.java
linux/cc/WindowManagerX11.hh
linux/cc/WindowX11.cc
linux/cc/WindowX11.hh
linux/java/WindowX11.java

Implements the X11 part of #135, along with `WM_CLASS` initialization; both only under `WindowX11` currently.

X11: setIconData and setClassHint

---

CMakeLists.txt
macos/CMakeLists.txt
shared/cc/StringUTF16.cc
shared/cc/StringUTF16.hh

`jchar` is an alias to unsigned char. And c++ std doesn't provide a `basic_string` specialisation for it anymore

Fix macos build
