.gitignore
CMakeLists.txt
macos/CMakeLists.txt

#7  It looks kinda weired for now since it has no complex logic, mb in the future we will extend it

Setup basic root cmake file (for clion project import)

---

linux/CMakeLists.txt
linux/cc/LayerGL.cc
linux/cc/WindowManagerX11.cc
linux/cc/WindowManagerX11.hh
linux/cc/WindowX11.cc
linux/cc/WindowX11.hh

Linux: resize without artifacts (flicker fix)

---

examples/java/org/jetbrains/jwm/examples/Example.java
shared/cc/impl/Library.cc
shared/cc/impl/Library.hh
shared/java/org/jetbrains/jwm/EventKeyboard.java
windows/cc/AppWin32.cc
windows/cc/AppWin32.hh
windows/cc/LayerGL.cc
windows/cc/LayerGL.hh
windows/cc/ScreenWin32.hh
windows/cc/WindowManagerWin32.cc
windows/cc/WindowWin32.cc
windows/cc/WindowWin32.hh

- Add modifiers for keyboard button event (closes #38)
- Add mouse button events (closes #39)

Windows: Mouse and keyboard button events

---

windows/cc/AppWin32.cc
windows/cc/AppWin32.hh
windows/cc/ContextWGL.cc
windows/cc/ContextWGL.hh
windows/cc/LayerWGL.cc
windows/cc/LayerWGL.hh
windows/cc/WindowManagerWin32.cc
windows/cc/WindowManagerWin32.hh
windows/cc/WindowWin32.cc
windows/cc/WindowWin32.hh
windows/java/org/jetbrains/jwm/WindowWin32.java

Windows: Multi-thread windows' event loop processing

---

examples/java/org/jetbrains/jwm/examples/Example.java
examples/java/org/jetbrains/jwm/examples/SkijaLayerRaster.java
shared/java/org/jetbrains/jwm/LayerRaster.java
windows/CMakeLists.txt
windows/cc/LayerRaster.cc
windows/cc/LayerRaster.hh
windows/cc/LayerWGL.cc
windows/cc/WindowManagerWin32.cc
windows/cc/WindowWin32.cc
windows/cc/WindowWin32.hh

Windows: raster backend

---

windows/cc/ScreenWin32.cc

fix screen position

---

.github/workflows/rebuild-docker-image.yaml

close #148
add workflow to rebuild linux docker image on Dockerfile change
please add secrets.DOCKER_USERNAME and secrets.DOCKER_PASSWORD for workflow to run.

add workflow to rebuild linux docker image

---

README.md
linux/cc/WindowManagerX11.cc
shared/cc/impl/Library.cc
shared/cc/impl/Library.hh
shared/java/EventWindowFocusIn.java
shared/java/EventWindowFocusOut.java

Implements focus events for X11 as in #185.

X11: Focus change events

---

linux/cc/WindowManagerX11.cc
linux/cc/WindowManagerX11.hh
linux/cc/WindowX11.hh

closes #129
(also makes the X error handler use stderr and flush for a much better development experience)

X11: Blocking event loop

---

examples/dashboard/java/Example.java
macos/cc/WindowMac.mm
macos/java/WindowMac.java

macOS Represented Filename

---

linux/cc/WindowManagerX11.cc

Lets input methods consume key press events to build compose/dead key sequences. Additionally keeps the currently focused window as the input context focus, otherwise multiwindow applications would only allow IMs to work on the newest opened window.
Closes #206

X11: support input methods

---

linux/cc/WindowManagerX11.cc

Does the same thing as other apps, resetting the scrolled distance every time the window is re-entered.

X11: reset scroll distance after re-entering window

---

linux/java/WindowX11.java
macos/java/LayerMetal.java
macos/java/WindowMac.java
macos/java/skija/LayerMetalSkija.java
shared/java/LayerGL.java
shared/java/LayerRaster.java
shared/java/Window.java
shared/java/skija/LayerGLSkija.java
shared/java/skija/LayerRasterSkija.java
windows/java/LayerD3D12.java
windows/java/WindowWin32.java
windows/java/skija/LayerD3D12Skija.java

Check whether is closed before invoking native methods

---

examples/dashboard/java/PanelScreens.java
linux/cc/WindowManagerX11.hh
linux/cc/WindowX11.cc
linux/cc/WindowX11.hh
linux/cc/WindowX11MotifHints.hh
linux/java/WindowX11.java

Use Motif hints to toggle the title bar visibility (borderless)

linux: adds setTitleBarVisible

---

docs/Getting Started.md
docs/GettingStarted.java

as per #239; added some extra comments, feel free to change

update Getting Started

---

linux/cc/WindowManagerX11.cc

Implements the fix proposed in #241

X11: Update mouse position in XI_Motion event (closes #241)

---

macos/cc/JWMMainView.mm

Wraps up #249
In the dashboard, if you do a four-finger swipe up then return to the window, the four touch points never get a chance to unregister and just stick around.  This fixes it by removing all touch points not present in the active touch event.

macOS: cancel absent touches

---

macos/cc/LayerMetal.mm
macos/java/LayerMetal.java

add GetMetalLayer for LayerMetal

add GetMetalLayer

---

linux/cc/WindowManagerX11.cc

X11: fix i3 workspace switching

---

linux/cc/WindowManagerX11.cc

Revert "X11: fix i3 workspace switching"

---

linux/cc/WindowManagerX11.cc

redo fix i3 workspace switching

---

README.md

Only checked X11 things; I'd assume more of the Windows & macOS things should be working too, but leaving that to someone who can check.

Update X11 info in readme
